### ISSUE TITLE
Remove node_modules/ from your project's Git

### ISSUE THREAD

**Issue by Sadykhzadeh** [aryankarim/Kurdchat-backend#1]
You don't need to push node_modules to the project's Git. Instead, add node_modules in .gitignore.
You can copypaste the [official Node.JS .gitignore recommendation](https://github.com/github/gitignore/blob/master/Node.gitignore) of GitHub

**Comment by Sadykhzadeh** [comment]
What's a problem to close issue if it's not actual? bruh.

**Comment by aryankarim** [comment]
@Sadykhzadeh where were you two years ago?
